package page.planr.android.core.data.auth

import android.security.keystore.KeyGenParameterSpec
import android.security.keystore.KeyProperties
import java.security.KeyStore
import javax.crypto.Cipher
import javax.crypto.KeyGenerator
import javax.crypto.SecretKey
import javax.crypto.spec.GCMParameterSpec

/** Symmetric encryption for secrets at rest (the OAuth session). */
interface TokenCipher {
    fun encrypt(plaintext: ByteArray): ByteArray

    /** Throws (e.g. `AEADBadTagException`) when [blob] was tampered with or the key changed. */
    fun decrypt(blob: ByteArray): ByteArray

    /**
     * Discards the key, so nothing encrypted so far decrypts again (the next
     * [encrypt] uses a new one). Throws when the key can't be discarded.
     */
    fun retireKey() {}
}

/**
 * AES-256-GCM. Blob layout: `[version=1][12-byte IV][ciphertext || 16-byte tag]`.
 * The IV is generated by the cipher on every encrypt (the Android Keystore
 * requires that), so a key is never reused with the same IV.
 */
class AesGcmTokenCipher(
    private val key: () -> SecretKey,
    private val retire: () -> Unit = {},
) : TokenCipher {

    override fun retireKey() = retire()

    override fun encrypt(plaintext: ByteArray): ByteArray {
        val cipher = Cipher.getInstance(TRANSFORMATION)
        cipher.init(Cipher.ENCRYPT_MODE, key())
        val iv = cipher.iv
        check(iv.size == IV_BYTES) { "Unexpected GCM IV length ${iv.size}" }
        return byteArrayOf(VERSION) + iv + cipher.doFinal(plaintext)
    }

    override fun decrypt(blob: ByteArray): ByteArray {
        require(blob.size > 1 + IV_BYTES && blob[0] == VERSION) { "Unknown token blob format" }
        val iv = blob.copyOfRange(1, 1 + IV_BYTES)
        val cipher = Cipher.getInstance(TRANSFORMATION)
        cipher.init(Cipher.DECRYPT_MODE, key(), GCMParameterSpec(TAG_BITS, iv))
        return cipher.doFinal(blob, 1 + IV_BYTES, blob.size - 1 - IV_BYTES)
    }

    private companion object {
        const val TRANSFORMATION = "AES/GCM/NoPadding"
        const val VERSION: Byte = 1
        const val IV_BYTES = 12
        const val TAG_BITS = 128
    }
}

/**
 * The session key, generated inside the Android Keystore (never exported).
 * Created lazily on first use and reused afterwards.
 */
object KeystoreSessionKey {
    private const val PROVIDER = "AndroidKeyStore"
    private const val ALIAS = "planr.session.v1"
    private const val KEY_BITS = 256

    @Synchronized
    fun getOrCreate(): SecretKey {
        val keyStore = KeyStore.getInstance(PROVIDER).apply { load(null) }
        (keyStore.getEntry(ALIAS, null) as? KeyStore.SecretKeyEntry)?.let { return it.secretKey }

        val generator = KeyGenerator.getInstance(KeyProperties.KEY_ALGORITHM_AES, PROVIDER)
        generator.init(
            KeyGenParameterSpec.Builder(ALIAS, KeyProperties.PURPOSE_ENCRYPT or KeyProperties.PURPOSE_DECRYPT)
                .setBlockModes(KeyProperties.BLOCK_MODE_GCM)
                .setEncryptionPaddings(KeyProperties.ENCRYPTION_PADDING_NONE)
                .setKeySize(KEY_BITS)
                .build(),
        )
        return generator.generateKey()
    }

    /** Deletes the key; [getOrCreate] makes a new one. */
    @Synchronized
    fun delete() {
        KeyStore.getInstance(PROVIDER).apply { load(null) }.deleteEntry(ALIAS)
    }
}
